### ISSUE TITLE
Campaign won't save timing info - gives the following error

### ISSUE THREAD

**Issue by precords** [thirdset/ThirdSetMauticTimingBundle#5] opened 2017-04-26 18:17 UTC
I have the ThirdSetMauticTimingBundle installed but and did everything in the instructions but am getting the following error when simply clicking the work hours on a campaign and then saving it:

mautic.NOTICE: PHP Notice - Undefined index: timing - in file ../mautic/plugins/ThirdSetMauticTimingBundle/EventListener/DoctrineSubscriber.php - at line 97 [] []

Change are not saved in the campaign and this is the error I get. Any ideas how to get this plugin working correctly.

Please help me solve this!
Thank you!

**Comment by collinkrawll** [comment] 2017-04-26 19:20
Hmm, I just tried it and couldn't reproduce the issue.

It looks like it has to do with your session data. Please try clearing your Mautic cache and restarting your web server.

If that doesn't work, please provide some additional info:

- Are you working with a campaign event that existed before installing the plugin?
- What version of Mautic are your running?
- Is the event that you are working with a Send Email event or something else?

**Comment by precords** [comment] 2017-04-26 20:03
yes campaign event ocurred before plugin, running 2.71, yes send email.   Will try clearing cache and restarting server.

**Comment by precords** [comment] 2017-04-26 20:28
well tried clearing cache and rebooting cache twice to no avail.   Even tried a new campaign as well to no avail....

**Comment by collinkrawll** [comment] 2017-04-26 21:59
I just did a fresh install of Mautic 2.7.1, created a campaign, installed the plugin, added the timing info and everything worked.  I then created another campaign and it worked again. I checked the mautic log and apache log and didn't see any errors.

Some more questions (sorry):

- Where are you seeing the error? The mautic log (app/logs/...)?
- When are you seeing the error? When you save the event? When you save the campaign? Are you saving the campaign with "Save and Close" or "Apply"?
- Are you able to see the "Timing" plugin when going to the gear (top right) and then plugins?
- Does it return anything when you run the `php app/console doctrine:schema:update --dump-sql` console command?
- What method did you use for clearing the Mautic cache?
- Are you running any other plugins that don't come with Mautic by default?

**Comment by collinkrawll** [comment] 2017-04-26 23:24
Ok, I figured it out - sorry it took so long. Your error message says "Notice". This is a NOTICE level PHP error. NOTICE level errors are turned off by default in PHP. Once I turned them on, I was able to reproduce the issue.  You may want to turn those off (especially in production) as code with NOTICE level errors (though not perfect) will still work (unless you turn NOTICE level errors on).

The issue that was throwing the NOTICE level error is now fixed in v1.1.4 of the plugin. Please update.

**Closed as completed by collinkrawll** 2017-04-26 23:24 UTC
Labels: bug

**Comment by precords** [comment] 2017-04-27 04:33
Ok, so I click the apply, then save and close.   When I come back in to the campaign, all timing info is gone as if I hadn't put in at all.   Is it still there, just invisible?

**Comment by precords** [comment] 2017-04-27 04:42
Yes I see the timing plugin.  When I run the update dump sql command it says. "Nothing to update -  your database is already in sync... "

**Comment by precords** [comment] 2017-04-27 05:04
Ok updated and bug is solved.   I now see the timing info after updating.   THANK YOU FOR THIS GREAT PLUGIN!!!
