### ISSUE TITLE
Not working on 2.14?

### ISSUE THREAD

**Issue by MattPryze** [thirdset/ThirdSetMauticTimingBundle#15] opened 2018-08-10 21:44 UTC
I just set up the plugin and have been testing it out, however all timing settings are completely ignored.

![screenshot_146](https://user-images.githubusercontent.com/18136493/43982635-c3e3f36e-9cc4-11e8-8a83-a555511fd674.png)

The timing settings should limit this email from sending only on Sunday, Saturday, and Wednesday between 11am and 3pm. However, the email gets sent whenever the cron job runs, as if the plugin doesn't exist. For example, 5pm on a Friday.

I have updated all database schema etc with no errors. Can anyone confirm this issue quickly please? Really need this resolved asap. No errors in log.

My email settings are set to queue.

And here are my cron jobs:
![screenshot_147](https://user-images.githubusercontent.com/18136493/43983133-f821675e-9cc6-11e8-8793-18244ca56581.png)

I also ran the phpunit tests and everything came back OK:
![screenshot_148](https://user-images.githubusercontent.com/18136493/43988553-3b9dd38e-9d06-11e8-9f05-5a3173176291.png)

Mysql database shows the timing settings where in fact saved:
![screenshot_149](https://user-images.githubusercontent.com/18136493/43988559-88c24fb4-9d06-11e8-8cd9-a4aecc9c87b4.png)

Thanks for your time.

**Comment by MRG95** [comment] 2018-08-12 12:34
Getting pretty desperate...

**Comment by collinkrawll** [comment] 2018-08-12 17:43
Hi, sorry for the delay. I should have some time to test against 2.14 later today or tomorrow.

In the meantime, can you please confirm that the email is actually being sent. There are two things that happen when the campaign action is processed. First, it will be scheduled and second it will fire (send the email). Is the email definitely being sent at the wrong time or is it maybe just the first part where it is added to the calendar? This plugin will allow the first part to happen immediately but it will schedule the email to go out at the first date/time that matches your timing expression.

I'd recommend creating a test segment (with just your own email and contact info) and a test email and campaign. In the campaign, create an email action and set it to only go out on certain days of the week (pick days so that it will be scheduled a couple of days out). Trigger the campaign and then check the Mautic calendar. You should be able to see both steps on the calendar (the part where it was scheduled and the part where it will actually send). You shouldn't receive an email (until appropriate based on where the event is on the calendar)  Please try this and post back what happens.

**Comment by MattPryze** [comment] 2018-08-12 17:55
Hello! Yes that is how I tested this in the first place. A fresh Mautic installation, 1 test campaign, 1 email, 1 contact. The emails get sent out whenever my cron job runs, regardless of what the plugin says. I have also tested this on all other campaign action types and they all behave as if the plugin doesn't exist at all.

(Checking the calendar now)

Thanks for looking into this :)

**Comment by collinkrawll** [comment] 2018-08-12 18:01
Hmm, yeah there might be an issue with 2.14. Is there any way you can roll back to 2.13?

**Comment by MattPryze** [comment] 2018-08-12 18:10
I have no previous 2.13 configuration. I started using Mautic at 2.14 and am already using some 2.14 exclusive features like running contacts back through campaigns etc.

Rolling back as a permanent solution wouldn't be ideal, especially for others using this plugin who have more stake in their email marketing than I do. Then again I guess that depends on the exact problem 2.14 is causing.

Have you already identified the issue within 2.14?

This is no longer an 'asap' issue for me as I have reworked my schedule and have held off on the launch of my email list. I'm in no big rush or anything. :)

**Comment by collinkrawll** [comment] 2018-08-12 18:16
Oh, yeah, I was just suggesting rolling back as a temporary solution since you said it was urgent. 2.14 just came out a couple of weeks ago and unfortunately other commitments have kept us from testing with it yet. We do plan to support it. I'll post back here once we get the issue figured out. Sorry for the issues and thanks for your help troubleshooting.

**Comment by MattPryze** [comment] 2018-08-12 18:20
Okay sounds good. Thanks for your dedication :)

**Comment by MattPryze** [comment] 2018-08-12 18:26
Follow up on the calendar;  All events were fired and show up on today's date even though it was scheduled for wednesday.

**Comment by collinkrawll** [comment] 2018-08-14 18:28
Ok, I tested against 2.14.0 and was able to reproduce the issue. 

Unfortunately, I don't see any path to an easy fix. In Mautic 2.14.0, they deprecated the class that we were hooking (the [EventModel](https://github.com/thirdset/ThirdSetMauticTimingBundle/blob/master/Model/EventModel.php) class) and completely redesigned much of the way that contacts are processed through campaigns. 

From the evaluation that I've done thus far, it looks like the easiest solution is to completely override much of the [EventExecutioner](https://github.com/mautic/mautic/blob/master/app/bundles/CampaignBundle/Executioner/EventExecutioner.php) class. By default, this class works with a batch of events and a batch of contacts. The batches are passed around and modified as a group. We need to update the class to instead process the contacts and events individually. This is necessary so that we can evaluate each contact's time zone, etc when making scheduling decisions.

I'll keep working on this as time permits. I'm also going to mark this issue with a "help-wanted" tag.

**Comment by MattPryze** [comment] 2018-08-20 08:29
So I'm running down to the wire. Things with my current non-Mautic email autoresponder have changed out of my control and now my release date has bumped up drastically. As a result, I purchased a new server and installed Mautic 2.13.1 so I could make use of this plugin. However, as I expected, 2.13.1 is missing essential features I cannot do without in my campaigns (Jump to event action for example).

Even worse is that both of the exclusive features 2.14 offers that I am required to use are dependent on the batch implementation that broke this plugin. So I can't even merge those pull requests into 2.13.

So... yeah I'm pretty stuck right now hahaha. If any passersby think they can help, please do :heart:

**Comment by collinkrawll** [comment] 2018-09-01 23:53
Okay, this is fixed in the just released [v1.2.0](https://github.com/thirdset/ThirdSetMauticTimingBundle/releases/tag/1.2.0) of this plugin.

Sorry for the delay.

**Closed as completed** 2018-09-01 23:53 UTC
