### ISSUE TITLE
Issues with large campaign on 2.10.1?

### ISSUE THREAD

**Issue by mellsaid** [thirdset/ThirdSetMauticTimingBundle#9] opened 2017-09-21 16:08 UTC
Q|A

Anyone have an issue when executing large campaigns? The process been very slow in mautic leading to process taking a much longer time to process and emails are going out overnight and in the weekend outside the crontabs which are set 8-6..

Problem appeared since mautic 2.9 and we are unsure if its mautic or timing bundle..

A reference to the thread is here: https://github.com/mautic/mautic/issues/4687

**Comment by collinkrawll** [comment] 2017-09-22 16:26
The timing bundle rules are applied when the event is scheduled rather than when it is executed. So you should be able to see your scheduled events on your Mautic Calendar and they should be scheduled based on your timing rules. Once they are scheduled, it is up to Mautic (and your cron jobs) to execute them - this plugin doesn't touch them after they are scheduled.

In your configuration, are your emails set to send immediately or are you using the mail queue setting?

**Comment by mellsaid** [comment] 2017-09-22 16:43
Thanks @collinkrawll .. Its set to send immediately. That should work fine, correct?

We are struggling to pin down the cause so we are checking all routes..

**Comment by collinkrawll** [comment] 2017-09-22 17:46
Yes, immediately should work. Using the mail queue/spool allows you to break up the process of creating an email and actually sending it. Queuing them requires a separate console command/cron job. This document has a good summary of how it works: http://symfony.com/doc/current/email/spool.html

Are you using an email sending service like Amazon SES?

**Comment by mellsaid** [comment] 2017-09-22 19:43
Yes, we are using sparkpost.

We think the delay is happening due to mautic bug then in processing the
scheduled mail task?

Did have any problems with latest mautic updafe by any chance?

**Comment by Rikk03** [comment] 2017-10-30 11:52
I cant install this plugin since v2.11.0 update.  Here is how I tried.
1. Used SSH,
2. Uploaded Zip and unzipped, then renamed folder ThirdSetMauticResetBundle.
3. Cleared Cache,
4. Checked permissions.
5. Checked plugins to install.
6. Deleted zip and checked plugins again - nothing.

Plugin is not visible - nothing to install.

Can anyone reproduce this?

Any ideas how to resolve the problem.

**Comment by mellsaid** [comment] 2017-10-30 12:05
@Rikk03 

Delete the zip file. that worked for us as per #6

**Comment by Rikk03** [comment] 2017-10-30 12:12
Already deleted the zip.  Sorry for not adding it to the list, wouldn't have thought the zip presence would have made a difference.  Perhaps its something else you did that fixed it?

Well I'll trying repeating the steps over again to see if I can identify the cause.

**Comment by Rikk03** [comment] 2017-10-31 09:06
Tried again and still no joy, tried adding Mautic to the beginning of the name, just how the other plugin folders were named.

From ThirdSetMauticResetBundle to MauticThirdSetMauticResetBundle

Deleted cache and refreshed, still no joy.

Any other ideas?

**Comment by collinkrawll** [comment] 2017-11-01 15:30
Both users in this thread have reported that it is now working for them (also see Issue #10) . Closing.

**Closed as completed by collinkrawll** 2017-11-01 15:30 UTC
